# Generated by Django 5.2.6 on 2025-09-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dormitory', '0003_role_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Ushbu rolga beriladigan ruxsatlar (Django permissions)', related_name='roles', to='auth.permission'),
        ),
    ]
