# Generated by Django 5.2.6 on 2025-09-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0004_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_view_dashboard', "Dashboardni ko'rish huquqi"), ('can_manage_dormitory', "Yotoqxona ma'lumotlarini boshqarish"))},
        ),
    ]
