# Generated by Django 5.2.6 on 2025-10-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0005_alter_userprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
    ]
