# Generated by Django 5.2.6 on 2025-10-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0006_remove_student_room'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='student.student'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='student.student'),
        ),
        migrations.RemoveField(
            model_name='studentpaymentstory',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentPaymentStory',
        ),
    ]
